Description: (AutoScaling)(ELB)
Mappings:
  RegionMap:
    ap-northeast-1:
      '32': ami-afb09dc8
Resources:
  WebServerGroup:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      VPCZoneIdentifier: !Ref Subnets
      LaunchConfigurationName: !Ref LaunchConfig
      MinSize: 2
      MaxSize: 3
      TargetGroupARNs:
        - !Ref ALBTargetGroup
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 4cee1593-441e-4aa1-9566-182fc77f5f44
  NodeExpressInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      AvailabilityZone: ap-northeast-1a
      ImageId: !FindInMap
        - RegionMap
        - !Ref 'AWS::Region'
        - '32'
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref SGForBasicAccessibility
      KeyName: !Ref KeyNameYo
      Tags:
        - Key: Name
          Value: NodeExpressServer
      UserData: !Base64
        'Fn::Join':
          - ''
          - - |
              #!/bin/bash
            - |
              sudo apt-get update
            - |
              sudo apt-get install python-software-properties
            - |
              curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
            - |
              sudo apt-get install nodejs
            - |
              sudo apt-get install ruby-full -y python-pip
            - >
              wget
              https://aws-codedeploy-us-east-1.s3.amazonaws.com/latest/install
            - |
              chmod +x ./install
            - |
              sudo ./install auto
            - |
              cd /home/ubuntu
            - >
              git clone https://github.com/CHAOWEICHIU/wie-ci-cd.git
              app
            - |
              cd app
            - |
              npm install
            - |
              node index.js &
    Metadata:
      'AWS::CloudFormation::Designer':
        id: c2c95391-1ccf-44a3-8b31-4a9a9e0fc00e
  LaunchConfig:
    Type: 'AWS::AutoScaling::LaunchConfiguration'
    Properties:
      ImageId: !FindInMap
        - RegionMap
        - !Ref 'AWS::Region'
        - '32'
      InstanceId: !Ref NodeExpressInstance
      InstanceType: t2.micro
    Metadata:
      'AWS::CloudFormation::Designer':
        id: e5d26cb2-e857-4749-8a63-204da84e266c
  ApplicationLoadBalancer:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Scheme: internet-facing
      Subnets: !Ref Subnets
      SecurityGroups:
        - !GetAtt
          - SGForBasicAccessibility
          - GroupId
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 154fdfff-d5d6-41cb-8b38-6899262b7d5b
    DependsOn:
      - SGForBasicAccessibility
  LoadBalancerListener:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ALBTargetGroup
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 3cde900e-1dd9-4049-aeb2-488410738a4f
  ALBTargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 3
      Port: 80
      Protocol: HTTP
      UnhealthyThresholdCount: 5
      VpcId: !Ref VpcId
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 7ab6e83f-99c3-47b5-9b65-692794861aa4
  SGForBasicAccessibility:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'SSH, HTTP, HTTPS'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 559aa1c8-5f30-41ee-b20a-b327de811825
Parameters:
  KeyNameYo:
    Type: 'AWS::EC2::KeyPair::KeyName'
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  VpcId:
    Type: 'AWS::EC2::VPC::Id'
    Description: VpcId of your existing Virtual Private Cloud (VPC)
    ConstraintDescription: must be the VPC Id of an existing Virtual Private Cloud.
  Subnets:
    Type: 'List<AWS::EC2::Subnet::Id>'
    Description: The list of SubnetIds in your Virtual Private Cloud (VPC)
    ConstraintDescription: >-
      must be a list of at least two existing subnets associated with at least
      two different availability zones. They should be residing in the selected
      Virtual Private Cloud.
Outputs:
  URL:
    Description: URL of the sample website
    Value: !Join
      - ''
      - - 'http://'
        - !GetAtt
          - ApplicationLoadBalancer
          - DNSName
  ssh:
    Description: connection root EC2 Instance
    Value: !Join
      - ''
      - - 'ssh -i ''tokyo-wayne.pem'' '
        - ubuntu@
        - !GetAtt
          - NodeExpressInstance
          - PublicDnsName
Metadata:
  'AWS::CloudFormation::Designer':
    7ab6e83f-99c3-47b5-9b65-692794861aa4:
      size:
        width: 60
        height: 60
      position:
        x: 30
        'y': 300
      z: 1
      embeds: []
    154fdfff-d5d6-41cb-8b38-6899262b7d5b:
      size:
        width: 60
        height: 60
      position:
        x: 30
        'y': 90
      z: 1
      embeds: []
      ismemberof:
        - 559aa1c8-5f30-41ee-b20a-b327de811825
      dependson:
        - 559aa1c8-5f30-41ee-b20a-b327de811825
    3cde900e-1dd9-4049-aeb2-488410738a4f:
      size:
        width: 60
        height: 60
      position:
        x: 30
        'y': 200
      z: 1
      embeds: []
      isconnectedto:
        - 154fdfff-d5d6-41cb-8b38-6899262b7d5b
      isrelatedto:
        - 7ab6e83f-99c3-47b5-9b65-692794861aa4
    559aa1c8-5f30-41ee-b20a-b327de811825:
      size:
        width: 60
        height: 60
      position:
        x: 150
        'y': 90
      z: 1
      embeds: []
    c2c95391-1ccf-44a3-8b31-4a9a9e0fc00e:
      size:
        width: 60
        height: 60
      position:
        x: 260
        'y': 90
      z: 1
      embeds: []
      ismemberof:
        - 559aa1c8-5f30-41ee-b20a-b327de811825
    e5d26cb2-e857-4749-8a63-204da84e266c:
      size:
        width: 60
        height: 60
      position:
        x: 260
        'y': 300
      z: 1
      embeds: []
      isrelatedto:
        - c2c95391-1ccf-44a3-8b31-4a9a9e0fc00e
    4cee1593-441e-4aa1-9566-182fc77f5f44:
      size:
        width: 60
        height: 60
      position:
        x: 150
        'y': 300
      z: 1
      embeds: []
      isconnectedto:
        - 7ab6e83f-99c3-47b5-9b65-692794861aa4
      isassociatedwith:
        - e5d26cb2-e857-4749-8a63-204da84e266c
    88ae5efe-11a1-4c2e-a17c-cbae21c5d688:
      source:
        id: 154fdfff-d5d6-41cb-8b38-6899262b7d5b
      target:
        id: 559aa1c8-5f30-41ee-b20a-b327de811825
      z: 11
    80156752-c903-419e-917d-e299367f4879:
      source:
        id: 154fdfff-d5d6-41cb-8b38-6899262b7d5b
      target:
        id: 559aa1c8-5f30-41ee-b20a-b327de811825
      z: 12
    2d0a7cdb-50d8-4766-a4c8-508f3b4fea94:
      source:
        id: 154fdfff-d5d6-41cb-8b38-6899262b7d5b
      target:
        id: 9a946048-19d2-4454-a56c-541a742ce303
      z: 2
    61408763-04ad-481e-b0ef-7854726059cd:
      source:
        id: 154fdfff-d5d6-41cb-8b38-6899262b7d5b
      target:
        id: 9a946048-19d2-4454-a56c-541a742ce303
      z: 3
    2857e727-4902-40a7-a2a3-33b4b693dd86:
      source:
        id: 154fdfff-d5d6-41cb-8b38-6899262b7d5b
      target:
        id: 9a946048-19d2-4454-a56c-541a742ce303
      z: 2
    db849b71-a18f-4ac1-8bc4-b6f2c78a5500:
      source:
        id: 154fdfff-d5d6-41cb-8b38-6899262b7d5b
      target:
        id: 559aa1c8-5f30-41ee-b20a-b327de811825
      z: 2
    2c5db052-eaca-47da-be5b-da3910e97693:
      source:
        id: 154fdfff-d5d6-41cb-8b38-6899262b7d5b
      target:
        id: 559aa1c8-5f30-41ee-b20a-b327de811825
      z: 2
