version: 0.2
env:
  variables:
    key: "value"
phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - npm run line:message "Prepare To Build!"
      - npm run test
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - npm run line:message "Done With Build For r-r2"
artifacts:
  files:
    - './aws/Cloudformation/betaWeb.yml'
  discard-paths: yes
