version: 0.2
env:
  variables:
    key: "value"
phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - npm run test
  post_build:
    commands:
      - npm run line:message "Done With Post_build"
artifacts:
  files:
    - './aws/Cloudformation/betaWeb.yml'
  discard-paths: yes
