Description: Test Env
Mappings:
  RegionMap:
    ap-northeast-1:
      '32': ami-afb09dc8
Resources:
  SGForBasicAccessibility:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'SSH, HTTP, HTTPS'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  NodeExpressInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      AvailabilityZone: ap-northeast-1a
      ImageId: !FindInMap
        - RegionMap
        - !Ref 'AWS::Region'
        - '32'
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref SGForBasicAccessibility
      KeyName: !Ref KeyNameYo
      Tags:
        - Key: Name
          Value: NodeExpressServer
      UserData: !Base64
        'Fn::Join':
          - ''
          - - |
              #!/bin/bash
            - |
              sudo apt-get update
            - |
              sudo apt-get install python-software-properties
            - |
              curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
            - |
              sudo apt-get install nodejs
            - |
              sudo apt-get install ruby-full -y python-pip
            - >
              wget
              https://aws-codedeploy-us-east-1.s3.amazonaws.com/latest/install
            - |
              chmod +x ./install
            - |
              sudo ./install auto
            - |
              cd /home/ubuntu
            - |
              git clone https://github.com/CHAOWEICHIU/react-server-side-rendering-with-aws app
            - |
              cd app
            - |
              npm install
            - |
              npm run build
            - |
              npm run serve &
Parameters:
  KeyNameYo:
    Type: 'AWS::EC2::KeyPair::KeyName'
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Default: tokyo-wayne
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
Outputs:
  URL:
    Description: URL of for beta envv
    Value: !Join
      - ''
      - - 'http://'
        - !GetAtt
          - NodeExpressInstance
          - PublicDnsName
  ssh:
    Description: connection to EC2 instance
    Value: !Join
      - ''
      - - 'ssh -i ''tokyo-wayne.pem'' '
        - ubuntu@
        - !GetAtt
          - NodeExpressInstance
          - PublicDnsName
